-- IDMPOTENT SQL PATCH SKELETONS (AUTOGENERATED)
-- Review and adjust carefully before applying. Run in staging first.

-- Ensure enum type exists (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'user_role' AND n.nspname = 'public') THEN
    CREATE TYPE public.user_role AS ENUM ('admin','supplier','customer','ai_agent');
  END IF;
END $$;

-- After applying patches, re-run introspection and the admin createUser diagnostic.